// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW87A36WanPa4eZH_1gJeSKMMXo6ANAHs',
    appId: '1:851785690026:web:5be243a4d960280e91d9d3',
    messagingSenderId: '851785690026',
    projectId: 'kitapalver-ece59',
    authDomain: 'kitapalver-ece59.firebaseapp.com',
    storageBucket: 'kitapalver-ece59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCaqMpGf2r-T8JjZQDs6s3p30Iy8vnmmc',
    appId: '1:851785690026:android:e6cfaadff83676d891d9d3',
    messagingSenderId: '851785690026',
    projectId: 'kitapalver-ece59',
    storageBucket: 'kitapalver-ece59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8JTf9AGtOPWKm_UdfGgzKY6tSyvR8230',
    appId: '1:851785690026:ios:9faedccfeb17176791d9d3',
    messagingSenderId: '851785690026',
    projectId: 'kitapalver-ece59',
    storageBucket: 'kitapalver-ece59.appspot.com',
    iosClientId: '851785690026-9naf732ibqenejejj9r3b081l19usfdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitapAlVer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8JTf9AGtOPWKm_UdfGgzKY6tSyvR8230',
    appId: '1:851785690026:ios:9faedccfeb17176791d9d3',
    messagingSenderId: '851785690026',
    projectId: 'kitapalver-ece59',
    storageBucket: 'kitapalver-ece59.appspot.com',
    iosClientId: '851785690026-9naf732ibqenejejj9r3b081l19usfdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitapAlVer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW87A36WanPa4eZH_1gJeSKMMXo6ANAHs',
    appId: '1:851785690026:web:13938651275eddb791d9d3',
    messagingSenderId: '851785690026',
    projectId: 'kitapalver-ece59',
    authDomain: 'kitapalver-ece59.firebaseapp.com',
    storageBucket: 'kitapalver-ece59.appspot.com',
  );
}
